USE `USER_MANAGEMENT`; 



CREATE TABLE `CITY` (
	`CITY_ID` varchar(10) NOT NULL,
    `CITY_NAME` varchar(255),
	`STATE_ID` varchar(10),
    PRIMARY KEY (`CITY_ID`)
);

SELECT * FROM `USER_MANAGEMENT`.`CITY`;

INSERT INTO `CITY`(`CITY_ID`,`CITY_NAME`, `STATE_ID`) VALUE ("UP32","LUCKNOW", "UP");
INSERT INTO `CITY`(`CITY_ID`,`CITY_NAME`, `STATE_ID`) VALUE ("UP44","SULTANPUR", "UP");
INSERT INTO `CITY`(`CITY_ID`,`CITY_NAME`, `STATE_ID`) VALUE ("MH32","MUMBAI", "MH");


CREATE TABLE `STATE` (
	`STATE_ID` varchar(10) NOT NULL,
    `STATE_NAME` varchar(255),
	`COUNTRY_ID` varchar(10),
    PRIMARY KEY (`STATE_ID`)
);

INSERT INTO `STATE`(`STATE_ID`,`STATE_NAME`, `COUNTRY_ID`) VALUE ("MH","MUMBAI", "IND");
INSERT INTO `STATE`(`STATE_ID`,`STATE_NAME`, `COUNTRY_ID`) VALUE ("UP","UTTAR PRADESH", "IND");
INSERT INTO `STATE`(`STATE_ID`,`STATE_NAME`, `COUNTRY_ID`) VALUE ("KARNATAKA","KA", "IND");

SELECT * FROM `USER_MANAGEMENT`.`STATE`;



CREATE TABLE `COUNTRY` (
	`COUNTRY_ID` varchar(10) NOT NULL,
    `COUNTRY_NAME` varchar(255),
    PRIMARY KEY (`COUNTRY_ID`)
);

SELECT * FROM `USER_MANAGEMENT`.`COUNTRY`;
INSERT INTO `COUNTRY`(`COUNTRY_ID`,`COUNTRY_NAME`) VALUE ("IND","INDIA");



